### ISSUE TITLE
Can articles only be published if the publication date is same as today's date?

### ISSUE THREAD

**Issue by chugginselifesciences** [libero/publisher#112]
IJM have asked if it is necessary to only be able to publish articles when the dat set in Kriya matches today's date (technically "today" is based on the timezone of the "journal home country"  not the user's local timezone). 

Matteo said his preference would be 

1) The Libero dashboard ignores the date completely, and the article can be published at any time
2) The Libero dashboard shows the publication date, but if missed, articles can still be published via the dashboard without re-running from Kriya
3) If necessary he accepts that he would need to change the date and re-run from Kriya to publish on the required date but this is his least preferred option.

If any of these options are possible, I assume we would have to show on the journal the same date set in Kriya (and shown on the PDF) even though it is not technically the date/time that it was published. 

I think this is a question for both @Melissa37 and @thewilkybarkid - can/should it be possible for IJM to publish articles before or after the date set in Kriya? What date would be shown on the journal if this is the case?

Or do we need to force IJM to either publish on the date set in Kriya, or re-run from Kriya in Libero to change the date if missed or required earlier?

We will likely need to show feedback when a publication date is "overdue".

**Comment by Melissa37** [comment]
Hi @chugginselifesciences 
I think the other person to loop in is @lsh-0  as he's done a lot of the Lax work.

My understanding is that it causes a lot of manual technical problems if the dates don't match and it would be better to have warnings on Libero if the dates don't match.

I think the issue for Matteo is his understanding of the source of truth, which should be the XML and although it feels annoying, the XML is always changed by the production process and thus Kriya, not the hosting platform.

Happy to discuss further.

**Comment by chugginselifesciences** [comment]
Thanks @Melissa37. I thought that was the case but wanted to double check it should/will need to be the case for MVP.

What I'm trying to do in the Libero dashboard design is indicate clearly when something has a publication date of "today" to draw attention to it. If the date is not "today" then we don't provide the option to "publish now".

I think if today has passed (i.e. it's overdue) we need to show that too. Especially if the date needs changing in Kriya before publishing. Hopefully this will makes things clearer for IJM.

**Comment by Melissa37** [comment]
> What I'm trying to do in the Libero dashboard design is indicate clearly when something has a publication date of "today" to draw attention to it. If the date is not "today" then we don't provide the option to "publish now".

Can we talk about this some more? Need to ensure we cover different versions and perhaps then not having new dates...

**Comment by thewilkybarkid** [comment]
I've never understood why eLife doesn't use the date when the article was published, is this because of the PDF or another reason?

**Comment by chugginselifesciences** [comment]
@Melissa37 I'd be happy to walk you through the current designs and see what you think - please let me know a time that suits you. I've tested the designs with your team but I think it would be good to walk through it together to test a realistic scenario, what happens when uploading new versions, corrections etc.

If you like, you could take a look at the below link first. If you click on the blue dot to view the "tour point" and use the "Next" button it will explain the intended functionality. Alternatively, you can use the button in the bottom right corner to view all of the pages and jump to the "user testing " section at the end where you can click around and try it out.

I'll be adding a walkthrough of publishing an issue so I can share it with Matteo, but I think for MVP it will need to be exactly the same as publishing an article, only we show the issue name where we show the article name.

https://invis.io/UWQCNW398PR

**Comment by lsh-0** [comment]
hi guys, just chipping in my thoughts as to how things are rather than how they should be.

Lax is the application that stores the json serialisation of articles and serves it on the api. 

Lax handles publication dates set in the xml but also has the responsibility of setting non-version-1 publication dates as revisions are published. These revision dates are not stored in the xml.

Lax receives unpublished articles from Production and is sent a signal when the article is to be published. At this point, the date captured from the XML is set and is available to the public.

The process is the same for revisions, however when the signal to publish is sent, the publication date for the revision is a simple UTC timestamp.

I'm happy to answer any questions

**Comment by Melissa37** [comment]
>I've never understood why eLife doesn't use the date when the article was published, is this because of the PDF or another reason?

@thewilkybarkid we do use the date when published, but most articles are PoA'd first and so the date of publication is previous to the date of VoR publication.
We're planning to introduce all dates into the XML at some point this year (awaiting JATS update to DTD) so we can give a reason for each publication at the source.

I think we alll need to review what we've set up for eLife and think of how we can improve it, but for MVP and IJM we do need to carefully walk through his publication dates and check we're all on the same page and it will work.
For instance, he will publish an article with today's date.
Then this will be gathered into an "issue" and given issue and pagination information. Is he thinking there will be an additional publication date for this second version? Or it will retain the first date?
I am not sure of any implications of turn of year and having some content in issues with two different years...

@thewilkybarkid Matteo is coming in on Friday 15th March to discuss production with Ravi. Is it worth me adding you to the meeting? And @chugginselifesciences and @Maelplaine?

**Comment by chugginselifesciences** [comment]
@Melissa37 I'd be happy to join the meeting. I'll be joining the workshop tomorrow too so may be an opportunity to talk about it or at least make a note of these questions.

> he will publish an article with today's date.
> Then this will be gathered into an "issue" and given issue and pagination information. Is he thinking there will be an additional publication date for this second version? Or it will retain the first date?

If it helps, I think Matteo would be fine with the date of an issue gaining a single additional publication date (for the day it is due to be published), if it's easier. I'd assumed it would be treated the same as an article in the Libero dashboard. He would also be happy with forthcoming issues to only be in HTML if that makes things simpler. 

I'm not sure these really make things easier in terms of workflow or development, but worth noting in case.

**Comment by Maelplaine** [comment]
@Melissa37 I will be on holiday that day (Friday 15th March). Please let me know what the outcomes of this meeting are. We can organise a workshop with Matteo and the dev team after this meeting to list the tickets needed for publishing issues and do bulk publications.
