### ISSUE TITLE
Push latest tags of project Docker images

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#123]
Currently projects push only a tag named like a commit e.g. `28f5963604d5fe0859cca962b5396e3df88d46ca`.

We should also push a `latest` tag upon a new `master` version passing the tests.

## Tasks

- [ ] `browser`
- [ ] `content-store`
- [ ] `dummy-api`
- [ ] `pattern-library`
- [ ] `search`
- [ ] update `sample-configuration` defaults

**Comment by BlueReZZ** [comment]
Obsolete
