### ISSUE TITLE
Validate incoming and outgoing XML

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#161]
- Validate incoming xml articles are valid JATS XML
 - Validate generated outgoing xml is a valid libero/schema item

**Comment by GiancarloFusiello** [comment]
Currently blocked by #159

**Comment by GiancarloFusiello** [comment]
The relevant schemas need to be supplied before work can start on this.

**Comment by thewilkybarkid** [comment]
The outbound schema is configuration. Though could have easily have a default. (Though still don't think there should normally be runtime outbound validation.)

**Comment by GiancarloFusiello** [comment]
My understanding is that the body of requests to services that implement Libero Content API need to be structured specifically for consumption. Therefore, it's important to test that the structure is formatted correctly. This doesn't have to be done at runtime but should be tested. I think it is likely that adopters of Libero Publisher will want to validate/test the structure of requests for their own services they might build, and so, it would be beneficial for them to have a source of truth to validate against.

Regarding inbound validation, my understanding is that this is a requirement for the JATS-Ingester but a schema has not been supplied and therefore not implemented.

**Comment by thewilkybarkid** [comment]
> Regarding inbound validation, my understanding is that this is a requirement for the JATS-Ingester but a schema has not been supplied and therefore not implemented.

What do you mean by this?

**Comment by GiancarloFusiello** [comment]
> What do you mean by this?

Which schema should be used to validate incoming article documents?

**Comment by thewilkybarkid** [comment]
Referring to JATS versions or what? Still don't understand.
