### ISSUE TITLE
Add behaviour for list of authors and afflilations

### ISSUE THREAD

**Issue by davidcmoulton** [libero/publisher#162]
Should follow eLife's behaviour:

## When viewport < 730px
Collapsed state (default): show first author only with `et al` link that will expand the list to show all authors:
<img width="182" alt="Screenshot 2019-06-10 11 41 40" src="https://user-images.githubusercontent.com/2893480/59190579-fbe3fa80-8b74-11e9-8501-953edfda3468.png">

Expanded state: show all authors but no affiliations, and a control to collapse:
<img width="558" alt="Screenshot 2019-06-10 11 42 09" src="https://user-images.githubusercontent.com/2893480/59190626-18803280-8b75-11e9-9b3f-27979f0905a2.png">

## When viewport >= 730px
Limited state (default): show the first nine authors and first nine affiliations, with a `See more` link that will expand the list to show all authors and affiliations:
<img width="1166" alt="Screenshot 2019-06-10 11 43 14" src="https://user-images.githubusercontent.com/2893480/59190652-2b930280-8b75-11e9-8cde-b66d2d06cea3.png">

Expanded state: show all authors and affiliations, with a control to show the limited view:
<img width="1142" alt="Screenshot 2019-06-10 11 43 22" src="https://user-images.githubusercontent.com/2893480/59190673-3c437880-8b75-11e9-8f32-b10b0e4bcb24.png">

**Note:** there is no URL change accompanying an author / affiliation view change: articles always load in the default collapsed / limited state. 

## Related
- Blocked by #145 (add to template).
- Blocked by #146 (add styles).

**Comment by chugginselifesciences** [comment]
@gmaciocci The current plan in Libero for the article view (about 730px) is to show the first 9 authors and the `see all` expand component if there are more than 9.

Would it make sense to also change this in a later release to include the "last author" (with ellipsis), similar to the listings update? https://trello.com/c/0gZbt2sc/96-update-author-name-format-in-listings

I'm assuming currently the last author will be initially hidden on the article view if 10 or more authors. In this example the last author (Bernhard Zipfel) would appear on the listing but not the article view.

Proposed listing with 1st, 2nd ... last author:
![image](https://user-images.githubusercontent.com/41907215/67220793-54c87700-f422-11e9-9877-e561dce557a3.png)

Article view with 9 authors:

![image](https://user-images.githubusercontent.com/41907215/67220828-6447c000-f422-11e9-9c0c-3784e7737aa0.png)


Or with 1st 9 authors + last author:
![image](https://user-images.githubusercontent.com/41907215/67225549-5c404e00-f42b-11e9-9c93-64cecdda92c8.png)

**Comment by thewilkybarkid** [comment]
The ‘last author’ concept doesn’t exist in other disciplines, though guess they tend not to have as many authors?
