### ISSUE TITLE
Google Analytics and GTM

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#165]
## Problem / Motivation

- WHO Product & Marketing team
- WHERE on the demo instance
- WHAT GTM tracking code for users activities
- WHY we need to be able to assess the popularity of this demo instance

## Proposed solution

- Track the GA basic: visits, time spent, referrals...
- Track the clicks on the navigation menu and the article titles on the home page using GTM

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Clarification needed and assumptions

- Are we happy to use the same snippet of code as libero.pub
- An assumption

## Technical notes
- GTM code used on libero.pub:

Paste this code as high in the **<head>** of the page as possible:
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5QCJ2FM');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening **<body>** tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5QCJ2FM"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by discodavey** [comment]
@Maelplaine I have sent over the Tag Manager code to Douglass Digital to put in the product site. Have you added the site into the admin section of the Google Analytics admin?

**Comment by Maelplaine** [comment]
@discodavey Yes I have already created a new GA property and we are already using it track activities on Libero.pub

**Comment by discodavey** [comment]
DD have now added the Tag Manager code to the Product site.

**Comment by thewilkybarkid** [comment]
https://github.com/libero/browser/pull/101

**Comment by giorgiosironi** [comment]
There on https://demo.libero.pub/
