### ISSUE TITLE
Button pattern

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#17]
## Problem / Motivation
 
- WHO wants this? The journal stakeholder
- WHEN and WHERE do they want it? On various journal pages
- WHAT do they want? A button template to use in links
- WHY do they want this? For consistency of appearance and behavior (of buttons)

## Proposed solution

- A standard button template with styling

## Tasks

- [ ] A pattern bundling markup and CSS
- [ ] Use this pattern into a link in the navigation bars

## Clarification needed and assumptions

- No styling customisation is required at the moment
- Journals using libero are going to be happy to use eLife's design pattern for the MVP
> IJM is happy to use them

## Technical notes
- Button is implemented as a styled `<a>` element, at least for these static links
- More notes or suggestions
- Existing implementation: [markup](https://github.com/elifesciences/pattern-library/blob/c86d341d0789f6b9f3f7558723322a29803b5f82/source/_patterns/00-atoms/components/button.mustache), [schema](https://github.com/elifesciences/pattern-library/blob/c86d341d0789f6b9f3f7558723322a29803b5f82/source/_patterns/00-atoms/components/button.yaml)

## User interface / Wireframes

![image](https://user-images.githubusercontent.com/39725642/43779568-9a3d5396-9a50-11e8-94eb-3366bfbe5750.png)

**Comment by thewilkybarkid** [comment]
The pattern will be needed, but is no longer part of the global navigation.

**Comment by giorgiosironi** [comment]
Outdated as the pattern will be part of the ticket actually using it.
