### ISSUE TITLE
Rename Libero demo journal

### ISSUE THREAD

**Issue by BlueReZZ** [libero/publisher#206]
## Problem / Motivation
 
Change the name of `The Internal Journal of Demonstration` to `The Libero Demonstration Journal`

## Proposed solution

This name should apply wherever the configuration is read, and should be evident in the homepage header.

## Example
Desktop

![image](https://user-images.githubusercontent.com/578113/60597921-b4334600-9da3-11e9-9013-9ff18da7547e.png)

Mobile

![image](https://user-images.githubusercontent.com/578113/60597799-7a623f80-9da3-11e9-95bf-c7c9feb73401.png)

**Comment by thewilkybarkid** [comment]
https://github.com/libero/sample-configuration/pull/76
