### ISSUE TITLE
fix links without protocols and convert doi to full URL

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#209]
Some articles contain incomplete URLs and do not have a complete URL for DOI references.

On eLife's current journal platform there is code to correct these "on-the-fly": https://github.com/elifesciences/bot-lax-adaptor/blob/58318286ab8d07d206abe34b313f63ce51117d31/src/main.py#L351-L370

To avoid these issues in future, these should be fixed in the article xml itself, however, for the upcoming demo on July 10th 2019 a **temporary** fix will be added so articles can be displayed.

**Task**
- add missing protocols to references missing them
- remove `<object-id>` tags

**Comment by Melissa37** [comment]
Thansk @GiancarloFusiello I think this is one of the things we should discuss re a production process and future proofing in future.

There is the camp that think the XML should contain the full url
However, the other camp feel PIDs should not include prefixes that could be subject to change - eg http to https changed, Crossref/DOI foundation could potentially change the url as this would then break these links in the future.

Changing all XML and an archive of content on a cross journal/publisher platform would seem less desirable than changing a piece of code that could do this for everyone. Can this issue be another ticket raised for future discussion and decision making once 10th July is passed?

Thanks!

**Comment by GiancarloFusiello** [comment]
@Melissa37 Happy to discuss this further in person and devise a long term solution.

I'm making a note of temporary measures added and will collate them all into a single ticket for removal after the demo.

**Comment by Melissa37** [comment]
Fantastic, thanks! What is that ticket?

Should @FAtherden-eLife add his XML changes to the same ticket so all in one place?

**Comment by GiancarloFusiello** [comment]
> Fantastic, thanks! What is that ticket?
> 
> Should @FAtherden-eLife add his XML changes to the same ticket so all in one place?

No ticket as of yet. Let's catch up tomorrow and come up with a solution together.

**Comment by GiancarloFusiello** [comment]
Spoken to @FAtherden-eLife that removing the `<object-id>` tag should resolve issues with DOI and is likely to not be supported in future. Updating tasks.
