### ISSUE TITLE
Add links to text

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#217]
Add inline links.

## Tasks

- [x] Add to Browser (https://github.com/libero/browser/pull/104)
- [x] Add JATS support (https://github.com/libero/jats-support/pull/19)

## Notes

- Pattern is already available.
- JATS to support:
  ```xml
  <ext-link xlink:href="[uri]">[...]</ext-link>
  ```
  where `@xlink:href` is a HTTP(S) URI.

**Comment by BlueReZZ** [comment]
We still need to add links to the actual post in question. Current version is in a gist here: https://gist.github.com/BlueReZZ/81a6d1fe0295af957597752a331a24b8

**Comment by FAtherden-eLife** [comment]
@thewilkybarkid, in the future we also need to allow ftp protocol links (although this can be added at later date if needed).

**Comment by thewilkybarkid** [comment]
Thinking about it, the scheme doesn’t matter. Just needs to have one (ie be absolute), so `mailto`, `tel` or whatever will just work.
