### ISSUE TITLE
Article page: download icon clashes with title

### ISSUE THREAD

**Issue by davidcmoulton** [libero/publisher#218]
On an article page, the download icon clashes with the article title when there is no category list above the title.

Example:
https://unstable.libero.pub/articles/36545:

![Screenshot 2019-07-09 16 57 22](https://user-images.githubusercontent.com/2893480/60904261-a598d300-a26a-11e9-93d8-3e90c8d0955a.png)

**Comment by thewilkybarkid** [comment]
Can hopefully fix https://github.com/libero/pattern-library/pull/96#issuecomment-496413863 too.

**Comment by thewilkybarkid** [comment]
https://github.com/libero/pattern-library/pull/128

**Comment by thewilkybarkid** [comment]
https://github.com/libero/browser/pull/106
