### ISSUE TITLE
Investigate normalising jats content using XSLT 1.0

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#225]
Currently, @FAtherden-eLife , the `jats-ingester` and `browser` need to translate/modify XML documents in order for them to work with Libero Publisher services. The reason for this is because there are many versions JATS, and also, journals may have unique structure of their zip files.

Writing services for Libero Publisher would be greatly simplified if the structure of the data is normalised and deterministic.

One approach to do this is to use XSLT 1.0 as many languages support transforming xml documents using this method with the help of libxml2 and libxslt.

**Task**
- Investigate whether it's possible to normalise JATS documents using XSLT 1.0
- Investigate whether it's simpler to do this on a per journal basis

**Comment by giorgiosironi** [comment]
Our understanding is that this route is not viable due to the dependency of having people with XSLT expertise in organizations that adopt Libero. Should we close if this has been decided?

**Comment by FAtherden-eLife** [comment]
Yup, it can be used if necessary (of course), but ideally we shouldn't that reason.
