### ISSUE TITLE
Populate Research Categories / Subject Areas / MSA Milestone

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#228]
## Problem / Motivation
- WHO wants this?
Readers on a journal using Libero Publisher

- WHEN and WHERE do they want it?
The list of MSAs will be displayed on the home page

- WHAT do they want?
Display all the Research articles of one MSA on a page

- WHY do they want this?
So that readers interested in only one MSA don't need to go through some content that doesn't interest them

## Clarification needed and assumptions
Assumptions:
- Libero publisher needs a mechanism for loading/querying content by category/subject

Questions:
1) Should a list of categories be supplied or should the implemented solution provide an API for adding categories/subjects?
> AFAIK the requirements are for lists based on a title. This could be done at runtime (ie new name appears, so a new list is created). But, we know this wouldn't be the case for eLife, and instead they need to be treated as entities (ie they're things themselves, with their own data).

> As far how to populate them in that case, "correct" way is an API, but without a mechanism for interacting with them (in eLife we use the CMS) maybe configuration?

2) Should this be a separate service with its own database? If so, how does the front-end service request content by category?
>Probably. And through the API.

3) Should this consider multi-tenancy at this stage?
> I think "yes" too given that might mean a fundamentally different approach to how some of the technical implementation is done (e.g. how identifiers are segmented, how lists are grouped etc)

> Multi-tenancy is one of the types of consideration that we need to make now rather than rework later

4) Given that other Libero products will use this service, should this service use the Libero Content API (xml) or should it use JSON in the request body?
> API spec says XML.

5) Do we display all the articles types? 
> Yes for now but in the future some journals will exclude some article types (for example we won't display magazine content for eLife)

## Decision
We will support list of categories and subjects and not hierarchical trees

## User interface / Wireframes
Click on the Neuroscience MSA to understand the workflow:
https://projects.invisionapp.com/share/87QKCKGYKJD#/screens/347378983

![image](https://user-images.githubusercontent.com/39725642/62531717-db65b300-b83a-11e9-85ce-14c5211b8206.png)

A working example of similar on eLife: https://elifesciences.org/subjects/evolutionary-biology

**Comment by Maelplaine** [comment]
@BlueReZZ and @thewilkybarkid Can you answer Giancarlo's questions to unblock him?
Correct me if I am wrong, it looks like I can only help with questions 3. 
I would say 'yes' but I do not know the technical implications.

**Comment by thewilkybarkid** [comment]
Based on current understanding (but given the recent discussions likely to change):

> 1. Should a list of categories be supplied or should the implemented solution provide an API for adding categories/subjects?

AFAIK the requirements are for lists based on a title. This could be done at runtime (ie new name appears, so a new list is created). But, we know this wouldn't be the case for eLife, and instead they need to be treated as entities (ie they're things themselves, with their own data).

As far how to populate them in that case, "correct" way is an API, but without a mechanism for interacting with them (in eLife we use the CMS) maybe configuration?

> 2. Should this be a separate service with its own database? If so, how does the front-end service request content by category?

Probably. And through the API.

> 4. Given that other Libero products will use this service, should this service use the Libero Content API (xml) or should it use JSON in the request body?

API spec says XML.

**Comment by BlueReZZ** [comment]
> Should this consider multi-tenancy at this stage?

I think "yes" too given that might mean a fundamentally different approach to how some of the technical implementation is done (e.g. how identifiers are segmented, how lists are grouped etc)

Multi-tenancy is one of the types of consideration that we need to make now rather than rework later

**Comment by Maelplaine** [comment]
Thanks @BlueReZZ 
How about the other questions in the ticket description above? Who can answer them?

**Comment by GiancarloFusiello** [comment]
> Does this sound like a need for a generic "search" service... where you could search for all "published" articles of type "neuroscience"?

What you are describing above seems like a query rather than a search term.

**Comment by giorgiosironi** [comment]
> a generic "search" service... where you could search for all "published" articles of type "neuroscience"

> What you are describing above seems like a query rather than a search term.

This could both be implemented with faceted search or with (relational database? My assumption) queries, in both cases the solution is more extensive than the requirement which is to provide a single filter:

- faceted search would allow you to use multiple filters
- database queries could filter on any other available attribute as well

Going off the design other needs are there that are implemented in Continuum:

- order by descending (publication?) date
- pagination with default size 5 (or likely a similar number of items in this order of magnitude)

A simplification in the design seems to be that there are no images attached to a single subject. There is a name that is independent in general from the (numerical?) ID as far as I remember and a URL-friendly slug according to what we collected in https://github.com/libero/publisher/issues/230

> To make this multi-teneted

We haven't got to multitenancy yet as that design is likely to span multiple entities in Publisher (not just categories but article types or issues) and perhaps multiple product (Reviewer in fact).

**Comment by giorgiosironi** [comment]
Evolving into https://docs.google.com/document/d/1PmLD6NEiqpjKTnjW-n1Hho_G-znp5lW3ba8PGmOHnQE/edit#

**Comment by giorgiosironi** [comment]
Just for reference, ignore:
![Screenshot_2019-08-28 Subjects Journal CMS(1)](https://user-images.githubusercontent.com/160299/63854818-e8874500-c995-11e9-8eb8-9a14a534c733.png)

**Comment by giorgiosironi** [comment]
https://docs.google.com/document/d/1PmLD6NEiqpjKTnjW-n1Hho_G-znp5lW3ba8PGmOHnQE/edit?ts=5d662f5c# is reasonably complete on the XML side, but:

- would collect complete JATS xml samples when implementation starts
- Product to make a pass through the ? points
- cross-cutting requirements like multitenancy to be considered separately

(originally posted in the wrong place)

**Comment by giorgiosironi** [comment]
This has been continued on the backend side by @GiancarloFusiello and @BlueReZZ yesterday. Remains open for front end integration.

**Comment by giorgiosironi** [comment]
Closing as will naturally come up again after Technology adaptation.
