### ISSUE TITLE
Add strategies for retrieving article ID

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#231]
Implement the following strategies:

- if `article-id[@pub-id-type="publisher-id"]` then `article-id[@pub-id-type="publisher-id"]`
(preferred tagging)
- else if `article-id[not(@pub-id-type='pmid') and not(@pub-id-type='pmc') and not(@pub-id-type='doi')]` then that `article-id`
(article-id which isn't one of the other known types)
- else if `elocation-id` then `elocation-id`
(elocation-id used as article-id)
- else if `article-id[@pub-id-type="doi"]` then `article-id[@pub-id-type="doi"]`
(last resort)
- else **fail**

**Comment by FAtherden-eLife** [comment]
Logic with full paths:
- `/article/front/article-meta/article-id[@pub-id-type="publisher-id"]`
- `/article/front/article-meta/article-id[not(@pub-id-type='pmid') and not(@pub-id-type='pmc') and not(@pub-id-type='doi')]`
- `/article/front/article-meta/elocation-id`
- `/article/front/article-meta/article-id[@pub-id-type="doi"]`

**Comment by FAtherden-eLife** [comment]
FYI I updated the second XPath to account for the (unlikely case) where there are two `article-id`s.
