### ISSUE TITLE
Move Python Flask ping endpoint into separate repositories

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#233]
Creating new services for [libero/publisher](https://github.com/libero/publisher) must implement a `/ping` endpoint or similar. [libero/search](https://github.com/libero/search) service has already implemented for use with Python Flask.

**Tasks**
- [x] move ping into a separate repository and it ensure can be installed as a Python package
- ~use it from `search` ~ might be revisited anyway because of XML dependencies
- [x] use it from `scholarly-content-details`

**Comment by giorgiosironi** [comment]
Similar solution in Continuum, for PHP: https://github.com/elifesciences/ping-php
