### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#24]
## Problem / Motivation
- WHO readers
- WHERE in the header
- WHAT want to be able to navigate
- WHY discover more content

## Proposed solution

- A main navigation bar similar to the one used on eLife

## Tasks

- [ ] TBC

## Clarification needed and assumptions

- How is this menu going to be used by journals? 
- Could it be used by multi-journals publishers as the journal navigation bar?

## Technical notes
- TBC

## User interface / Wireframes

![IJPI-Home](https://user-images.githubusercontent.com/39725642/54269827-faa33180-4575-11e9-819e-9efe325f1595.jpg)

Prototype link: https://projects.invisionapp.com/share/87QKCKGYKJD#/screens/347378983

**Comment by Maelplaine** [comment]
@chugginselifesciences This Primary Nav bar could only contain the link "Home" for the MVP

**Comment by chugginselifesciences** [comment]
@Maelplaine We would therefore need to show all forthcoming articles and all issues on the home page. Can you confirm this is correct?

It would be the equivalent of this list on the right column. The forthcoming articles on the left column
![image](https://user-images.githubusercontent.com/41907215/48361960-7a89bf80-e69a-11e8-8f02-c9e944c26009.png)

The alternative would be an "issues" page, which we link to below a list of latest issues.  SImilar to the eLife homepage with a list of a few magazine articles in the right column, with a link to the magazine landing page at the bottom
![image](https://user-images.githubusercontent.com/41907215/48362048-af961200-e69a-11e8-8a2f-8368b06f48f6.png)

**Comment by Maelplaine** [comment]
@chugginselifesciences the second option is a good idea. We could also add "Issues" in the main menu

**Comment by davidcmoulton** [comment]
As agreed in person in the alignment meeting on 26th June, in the first instance this will contain the "Home" link only.

**Comment by thewilkybarkid** [comment]
Closing in favour of #140.
