### ISSUE TITLE
Expose way to add categories

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#246]
~Who does it influences the way we allow it to be done. IJM, service provider, us?~

Scope of this to be: an API is available on `scholarly-content-detail` to add categories as the service provide sees fit. This API can be the same that is used by `jats-ingester` to auto-create categories.

**Comment by Melissa37** [comment]
Publisher - different departments from editorial to production and marketing
Service provider - what is expected of them

Service provider has 2 meanings - the production vendor (who produce and deliver the XML) and the service provider hosting the site. We have to be careful about confusion between these two different roles and terminology.

**Comment by giorgiosironi** [comment]
Updated description with correct scope decided after discovery.

**Comment by GiancarloFusiello** [comment]
- Should categories be added one at a time, in bulk or both?
- Should the name be stored as received or sanitised before persisting?

**Comment by giorgiosironi** [comment]
My assumptions follow.

> Should categories be added one at a time, in bulk or both?

API should allow to add them one by one, and `jats-ingester` should add them one by one

> Should the name be stored as received or sanitised before persisting?

As of this ticket, store as-is and no transformation should be performed. The specification of https://github.com/libero/publisher/issues/242 confirms it.

**Comment by GiancarloFusiello** [comment]
>API should allow to add them one by one, and jats-ingester should add them one by one

When should the `jats-ingester` add a category to the `scholarly-content-detail` service?

**Comment by GiancarloFusiello** [comment]
Ok I can see in https://github.com/libero/publisher/issues/245 it states:
> POST or PUT on the category, autocreating it, if not already present.

Ignore my question above.

**Comment by GiancarloFusiello** [comment]
@giorgiosironi should the `id` of the newly created/updated entry be returned in the response?

**Comment by GiancarloFusiello** [comment]
@giorgiosironi The [http specification](https://www.ietf.org/rfc/rfc2616.txt) under section 10.2.2 201 Created states a `Location` header can be added to the response. I'll use this.

**Comment by giorgiosironi** [comment]
Good for me, it's very RESTful. The `id` can be fetched by the client, if required, by following the `Location` header.
