### ISSUE TITLE
Discovery: investigate how patterns might be used with a JavaScript web app

### ISSUE THREAD

**Issue by BlueReZZ** [libero/publisher#248]
## Problem / Motivation
 
- Developers and service providers want a more consistent way across our product suite to apply changes to or build front-ends
- We need to ensure we have a frustration-free and clear way to work with patterns and JavaScript web apps for Publisher that could be used in alignment with Reviewer and other products

As a pre-requisite and driver for front-end tasks to complete https://github.com/libero/publisher/issues/228
## Proposed solution

-  Explore the use of patterns with the current way we build front-ends in Reviewer for use in the context of Publisher
- Use the goal of getting the categories listing page in https://github.com/libero/publisher/issues/228 to explore these ideas
- Agree a common way forward and raise tickets to build the first iteration

## Prerequisite
Good user-related front end principles are maintained.

**Comment by davidcmoulton** [comment]
Everything we build for the front end should reflect these front end development principles which champion users: https://docs.google.com/document/d/1Hi9RLLyfB7xRRVUg2dsfTJndHTXXlzU_eHNKE8BhcZ4/edit

**Comment by davidcmoulton** [comment]
Discovery document: https://docs.google.com/document/d/1FkdvBjSb1BH1fhgujtppunvL_NX5U3xVuxv7L0fV010/edit#
