### ISSUE TITLE
Investigate more JATS models for MVP

### ISSUE THREAD

**Issue by FAtherden-eLife** [libero/publisher#249]
## XML samples to test
- [x] Wellcome open res
- [x] Gates open res
- [x] F1000

All umbrella'd under F1000 open research.

Definition of Done
- Potential variants with previously investigated models identified
- State common choices made (e.g. MathML vs LaTex)

**Comment by FAtherden-eLife** [comment]
- 666 Wellcome open res articles - [list of all elements](https://github.com/libero/publisher/files/3600739/wellcome-all-elems.xml.zip)
- 5244 F1000 open res articles - [list of all elements](https://github.com/libero/publisher/files/3600743/f1000-all-elems.xml.zip)
- 145 Gates open research articles - [list of all elements](https://github.com/libero/publisher/files/3601544/gates-all-elems.xml.zip)

**Comment by FAtherden-eLife** [comment]
Variances:
- has `sub-article`
- has ` styled-content` - used for colour
- use `uri` for ORCiDs
- `corresp/fn` in `author notes` for corresponding author text
- use `role` for contributions (eLife will use this going forward)
- Noting no use of `fig-group` or `table-wrap-group`

Choices:
- `elocation-id` and `article-id[@pub-id-type="doi"]` used
- use `mixed-citation` instead of `element-citation`
- `mml:math` instead of `tex-math`


(Incomplete)

**Comment by giorgiosironi** [comment]
Going to post here a way to access the biorxiv content samples.

**Comment by giorgiosironi** [comment]
@FAtherden-eLife you should have access to `test-elife-mirror-biorxiv-src-monthly` now, can you confirm?

**Comment by FAtherden-eLife** [comment]
@giorgiosironi thanks, confirming I have access.

**Comment by FAtherden-eLife** [comment]
Closing. bioRxiv content tracked in https://github.com/libero/publisher/issues/253
