### ISSUE TITLE
Add log rotation to Elasticsearch

### ISSUE THREAD

**Issue by GiancarloFusiello** [libero/publisher#254]
In an attempt to save disk space where possible, adding log rotation to elasticsearch would help with fulfilling this objective.

**Tasks**
- [x] Add a volume `data-search-logs` similar to [`data-search`](https://github.com/libero/sample-configuration/blob/master/docker-compose.yml#L150)
- [x] Add log rotation with a delete policy of 30 days. See [elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/logging.html) for guidance.

**Comment by giorgiosironi** [comment]
Added a checklist item for a logs volume. We don't just want the logs to be there to avoid the container being filled with them invisibly until a deploy happens; it's also useful to look at them for debugging or for understanding what is fillind the disk.
