### ISSUE TITLE
Create hypermedia-based walking skeleton

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#265]
- 1 front-end app
- 1 back-end app
- Monorepo
- Run from source
- Node.js
- Bare HTML output
- Understands [`http://schema.org/Article`](http://schema.org/Article) and [`http://schema.org/name`](https://schema.org/name)
  - Will pass through unknown properties
- Has [`CreateArticle`](https://schema.org/CreateAction) and [`Search`](https://schema.org/SearchAction) actions
- Ignore server-sent events
- JSON-LD only

**Comment by thewilkybarkid** [comment]
Work going on in https://github.com/elifesciences/libero-hypermedia-walking-skeleton.

**Comment by giorgiosironi** [comment]
Why `elifesciences` as an organization?

**Comment by giorgiosironi** [comment]
Gave a shot at running it, but not ready yet. 
`GET http://localhost:8081/` seems to attempt to create `back-end/db/articles` every time is loaded, and `back-end/db` is initially missing from the checkout.

**Comment by giorgiosironi** [comment]
Current issues after trying this out locally follow.

## Slow homepage

```
Front-end started at http://localhost:8080
Back-end started at http://localhost:8081
  <-- GET /
[Axios][Request] 2019-10-04T11:02:41+0100 / GET
  <-- GET /
  --> GET / 200 11s 457b
  --> GET / 200 18s 838b
  <-- GET /
[Axios][Request] 2019-10-04T11:03:22+0100 / GET
  <-- GET /
  --> GET / 200 10s 457b
  --> GET / 200 21s 838b
```
Not really sure what it is doing for 10s of seconds, some timeout happening?

## Error on creating an article

```
  <-- POST /articles
  xxx POST /articles 500 380ms -

  SyntaxError: Invalid regular expression: /^(?<property>http:\/\/schema\.org\/(?<name>.+?))-input$/: Invalid group
      at Object.keys.forEach (/home/giorgio/code/libero-hypermedia-walking-skeleton/front-end/src/routes/create-article.ts:26:31)
      at Array.forEach (<anonymous>)
      at /home/giorgio/code/libero-hypermedia-walking-skeleton/front-end/src/routes/create-article.ts:25:29
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by giorgiosironi** [comment]
Is `/actions` supposed to cover article actions or all actions in general? The latter would sound suspiciously RPC-oriented.

**Comment by thewilkybarkid** [comment]
> Slow homepage

Weird, can't replicated. Avoided Docker as couldn't quickly get Nodemon working.

> Error on creating an article

Hmm, wonder if there's a different in the regex engine on MacOS and Linux.

> Is `/actions` supposed to cover article actions or all actions in general? The latter would sound suspiciously RPC-oriented.

Can be either. Since you shouldn't be handcrafting URIs, the client won't care. Unsafe-actions-as-a-resource does sound similar to RPC, but it isn't (it's like DDD rather than CRUD).

**Comment by giorgiosironi** [comment]
> Hmm, wonder if there's a different in the regex engine on MacOS and Linux.

Will debug

> Unsafe-actions-as-a-resource does sound similar to RPC, but it isn't (it's like (DDD) commands rather than CRUD).

Kind of a Command Bus, must put those additional semantics somewhere on top of the standard HTTP methods

**Comment by giorgiosironi** [comment]
Upgrading from Node 8 to Node 10 fixes the regex, but not the performance.

**Comment by thewilkybarkid** [comment]
Started to add a README. Will comment in the code too.

**Comment by thewilkybarkid** [comment]
Could you take a look @giorgiosironi @BlueReZZ?

**Comment by thewilkybarkid** [comment]
Now Dockerised.

**Comment by giorgiosironi** [comment]
Questions:
1. Didn't understand the line in the logs `front-end_1  |   --> POST /articles 303 67ms 33b` as the API seems to describe `POST /actions` (not just with this type of action) to accomplish that? I guess that's the front end receiving rather than requesting.
1. What's in `back-end/db/`? I create articles but they remain empty.
1. https://github.com/elifesciences/libero-hypermedia-walking-skeleton/blob/master/front-end/src/routes/create-article.ts#L17 doesn't need to find the action as much as it needs to decode the hidden field in the form request? The latter seems more consistent.

**Comment by thewilkybarkid** [comment]
> 1. Didn't understand the line in the logs `front-end_1  |   --> POST /articles 303 67ms 33b` as the API seems to describe `POST /actions` (not just with this type of action) to accomplish that? I guess that's the front end receiving rather than requesting.

Yep; added https://github.com/elifesciences/libero-hypermedia-walking-skeleton/commit/c9b56dbb5690e8937b15e99fc643b64e7760f96d.

> 2. What's in `back-end/db/`? I create articles but they remain empty.

https://github.com/elifesciences/libero-hypermedia-walking-skeleton/commit/64172ef6dcf6e89d03e24b5048c915481a17bb0b

> 3. https://github.com/elifesciences/libero-hypermedia-walking-skeleton/blob/master/front-end/src/routes/create-article.ts#L17 doesn't need to find the action as much as it needs to decode the hidden field in the form request? The latter seems more consistent.

That's all a hack (like https://github.com/elifesciences/libero-hypermedia-walking-skeleton/blob/c9b56dbb5690e8937b15e99fc643b64e7760f96d/front-end/src/routes/search.ts#L20-L21). Really it should be cached and the key passed in a hidden field.

> 4. https://schema.org/result is a strange name, prescribes the result of the action ("John wrote a `book`" in the example) but same actions may produce different results. The protocol seems to use it as the [input for the action](https://github.com/elifesciences/libero-hypermedia-walking-skeleton/blob/master/front-end/src/routes/create-article.ts#L26-L32) rather than for the output?

For this type of action, yes. The result of 'creating an article' is an article. The value of this changes between an active/failed action and completed action.

Other types of actions won't have a `result` (take a look through https://sci.pe/get-started/api#action-reference).

> 5. Does https://github.com/elifesciences/libero-hypermedia-walking-skeleton/blob/master/front-end/src/routes/create-article.ts#L49-L53 check the response status or what should it check?

It'll error (see https://github.com/elifesciences/libero-hypermedia-walking-skeleton/blob/c9b56dbb5690e8937b15e99fc643b64e7760f96d/front-end/src/routes/article.ts#L23-L33).

**Comment by thewilkybarkid** [comment]
> 6. My general idea for a next step would be to introduce the wrappers the README is proposing to see how clean can the domain layer made to be if the complexity is hidden.

Started looking at rdflib.js again, opened https://github.com/linkeddata/rdflib.js/issues/364 as I can't get JSON-LD to work. However, it can handle other format so can persevere with that.

**Comment by giorgiosironi** [comment]
Not understanding why https://schema.org/target can also be a string, as that page clearly says it can only be a https://schema.org/EntryPoint; then the example 1 of https://schema.org/EntryPoint shows alternating between the `"@type": "http://schema.org/EntryPoint"` dictionaries and simple strings containing URLs. https://schema.org/docs/actions.html also uses the string format throughout.

**Comment by thewilkybarkid** [comment]
Suspect they mean `EntryPoint or URL` like https://schema.org/image. Worth creating an issue on https://github.com/schemaorg/schemaorg if there isn't one already.

**Comment by giorgiosironi** [comment]
Haven't got to the persistence side yet, but clearly the filesystem would be substituted by a database in a real environment. The data doesn't really look relational, `sci.pe` seems to use [CouchDB with a few search extensions](https://github.com/science-periodicals/app-suite#cloudant-couchdb-2x--clouseau--dreyfus).

**Comment by giorgiosironi** [comment]
> http://schema.org/target can also be a string

http://schema.org/result is also [implemented here with a URL](https://github.com/elifesciences/libero-hypermedia-walking-skeleton/blob/master/back-end/src/routes/post-action.ts#L40) rather than with the `{"@type":"http://schema.org/...", ...}` dictionary. I guess that's always allowed? Is it a JSON-LD idiom? Where's the best place to find all the possible cases rather than reading the whole spec?

**Comment by thewilkybarkid** [comment]
> http://schema.org/result is also [implemented here with a URL](https://github.com/elifesciences/libero-hypermedia-walking-skeleton/blob/master/back-end/src/routes/post-action.ts#L40) rather than with the `{"@type":"http://schema.org/...", ...}` dictionary. I guess that's always allowed? Is it a JSON-LD idiom? Where's the best place to find all the possible cases rather than reading the whole spec?

Think that's wrong, should be `"result": {"@id": "..."}`.

JSON-LD is not easy, and contexts can change how things work. With the current raw string, it's expanded to be `@value` rather than `@id`, but you can set a context to make that work. (This allows JSON-LD to be mapped independently onto existing JSON.) Playing around in https://json-ld.org/playground/ and https://search.google.com/structured-data/testing-tool can be useful.

**Comment by giorgiosironi** [comment]
Persistence mechanism is meant to be a relational database with a JSON column type like Postgres. Objects being represented as JSON-LD, we want a normalization step of its different forms before persistence for ease of querying.

**Comment by giorgiosironi** [comment]
Splitting https://github.com/libero/publisher/issues/277
