### ISSUE TITLE
Investigate Airflow operators compatible with JavaScript code

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#270]
- [x] `BashOperator`, how does it look like?
  - [x] How does XCom work, if it does, with the `BashOperator`?
    - [x] return values
    - [x] access to values from previous tasks
  - [x] install `node` in the container is viable?
  - [x] standard output and error from the process are logged somewhere?
  - [x] can we still pass the correct templated variables into tests without Python (or a tiny bit of Python)?
- [x] `DockerOperator`, how does it look like?
- [x] Any Operator for Kubernetes/Helm?

/cc @GiancarloFusiello

**Comment by GiancarloFusiello** [comment]
List of official [Apache Airflow Operators](https://github.com/apache/airflow/tree/master/airflow/operators) and [contributed Operators](https://github.com/apache/airflow/tree/master/airflow/contrib/operators)

- [Bash Operator](https://airflow.readthedocs.io/en/latest/howto/operator/bash.html)
- [Docker Operator](https://github.com/apache/airflow/blob/master/airflow/operators/docker_operator.py#L36)


Here is the [Kubernetes section in the official documentation](https://airflow.readthedocs.io/en/latest/kubernetes.html) which states there is a [KubernetesPodOperator](https://airflow.readthedocs.io/en/latest/howto/operator/kubernetes.html) in the `airflow.contrib.operators` library. 

[The Kubernetes Executor documentation](https://airflow.readthedocs.io/en/latest/executor/kubernetes.html) mentions Helm charts but not in detail.

**Comment by giorgiosironi** [comment]
Questions:
1. Where would the `BashOperator` execute in the context of `jats-ingester? Inside the Airflow worker container?
2. How would the `DockerOperator` work in the same context? There are ways to do Docker-in-Docker, I would assume the Airflow worker container needs access to a Docker socket or Docker daemon HTTP endpoint?
3. What's the difference between Operator and Executor in Airflow? Especially in the context of Kubernetes.

**Comment by GiancarloFusiello** [comment]
> 1. Where would the `BashOperator` execute in the context of `jats-ingester? Inside the Airflow worker container?

Yes.

> 2. How would the `DockerOperator` work in the same context? There are ways to do Docker-in-Docker, I would assume the Airflow worker container needs access to a Docker socket or Docker daemon HTTP endpoint?

Executes a command inside a docker container. The image can be local or pulled from a repository. The docker daemon/engine is required which is not ideal as the workers are already running in docker containers.

> 3. What's the difference between Operator and Executor in Airflow? Especially in the context of Kubernetes.


[Operators](https://airflow.readthedocs.io/en/stable/concepts.html#operators)
[Executors](https://www.astronomer.io/guides/airflow-executors-explained/)

**Comment by giorgiosironi** [comment]
Created https://github.com/libero/publisher/milestone/23 conditionally to the fact that this investigation is successful. If so, we'll populate it with tasks to port the current `process_article_zip` tasks related to XML to JavaScript and deploy them to the `demo` environment.

**Comment by GiancarloFusiello** [comment]
>How does XCom work, if it does, with the BashOperator?
 
XCom values can be accessed when rendering the `bash_command` field. Meaning the XCom value would be a passed argument to the cli arguments.

> install node in the container is viable?

yes


> standard output and error from the process are logged somewhere?

It is but limited to the last call to `console.log` from what I can see. Also, in order to "return" data from the task, it must be called by `console.log` rather than returned.

> can we still pass the correct templated variables into tests without Python (or a tiny bit of Python)?

Depending on the test, for most cases there is minimal code needed for python tests. I can create facades for test setup.

**Comment by GiancarloFusiello** [comment]
As discussed in person, will update tasks to use AWS S3 bucket for storing the resulting XML of tasks. XCom will be used to return the S3 Key of the resulting XML from the previous task rather than returning the resulting XML.

@giorgiosironi any preferences regarding a name for the new bucket? `/completed-tasks`?

**Comment by giorgiosironi** [comment]
This is a bucket that can in general be used to store the result of tasks, in this case XML documents but it could in theory be any blob. The name seems to fit, given the naming convention in a real environment this would be `unstable-jats-ingester-completed-tasks` but in terms of variable names, config keys etc. using the name `completed tasks` in some form is alright.

**Comment by GiancarloFusiello** [comment]
[Pull request](https://github.com/libero/jats-ingester/pull/59) is available replacing a single python task with one written in Javascript.

Also, PR for `sample-configuration` is available https://github.com/libero/sample-configuration/pull/82 with changes required for the above PR.

@giorgiosironi we will need a new bucket with a suffix of `completed-tasks` for both environments. Can these be created using the AWS console web interface or do we need to provision these somehow?

**Comment by giorgiosironi** [comment]
> we will need a new bucket with a suffix of completed-tasks for both environments. 

https://github.com/libero/infrastructure/ is the way to go, there are already `jats-ingester` buckets there if you want to try a copy&paste approach for the new ones?

**Comment by GiancarloFusiello** [comment]
- `completed-tasks` bucket added to both environments
- deployed bash operator running javascript tasks using nodejs to both environments
- observed DAGs completed successfully in both environments

Closing this investigation ticket.
