### ISSUE TITLE
Investigate a substitute for Airflow more sympathetic to JavaScript

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#271]
@GiancarloFusiello to do some research and fill in options for this investigation.
Once we have a few options, we can define together some metrics such as;
- [ ] footprint: how many containers do you run? How much memory is used? (second-hand experience)
- [ ] language
- [ ] maintenance
- [ ] integrations e.g. S3

/cc @BlueReZZ are there implicit reasons (that we are not aware of) for favoring Airflow over other platforms?

**Comment by BlueReZZ** [comment]
The main benefit AirFlow added over a standard programmatic way of achieving the same was the additional UI that a technically astute staff member might use for monitoring or debugging issues. I presume alternatives might offer the same so perhaps this should be a extra checkbox in the description.

A compelling reason to keep it would be that it's also used in Libero Data Hub. There are other considerations around taking advantage of that though (coupling, using a single instance, the likely uptake of Data Hub versus Publisher) so it's not a overriding goal.

**Comment by GiancarloFusiello** [comment]
After a brief online search, I cannot see anything similar to Apache Airflow in the Javascript world.

The main components Libero Publisher would need to reproduce the current solutions provided by Airflow DAGs are:
- a message queue
- an XML parser
- a media converter
- an admin interface?

The main benefits that Apache Airflow provides are:
- an admin UI (as @BlueReZZ mentioned above)
- a scheduler
- scalability (ability to have N number of workers to pop tasks off the queue)

**Comment by giorgiosironi** [comment]
Close as not viable then?

**Comment by BlueReZZ** [comment]
I'd prefer to see the effort put into the outcomes of https://github.com/libero/publisher/issues/270 given AirFlow as a piece of infrastructure is very good and we've had a lot of investigation into confirming that. The lists of existing operators suggest that there may be options other than a programming language to achieve what we need (eg. there are HTTP, SFTP, S3 operators)
