### ISSUE TITLE
Airflow knowledge sharing

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#272]
Knowledge sharing about the Airflow setup in `jats-ingester`, to be achieved in person and/or with written documentation.

- [x] current architecture
- [x] possible near-term features
- [x] pain points
- [x] future long-term roadmap, to be informed by wider architectural decisions

/cc @GiancarloFusiello

**Comment by giorgiosironi** [comment]
Share an agenda before meetings that are meant to propagate this knowledge.

**Comment by GiancarloFusiello** [comment]
Agenda
--------

Architecture:
- what is deployed/required to run airflow
- project structure

Roadmap:
- next steps

Pain points:
- barrier to entry
- testing
- maintenance

Reflection:
- How does using airflow help?
- Could you use something else?

**Comment by GiancarloFusiello** [comment]
@giorgiosironi I don't remember what were the near term features. Do you?

**Comment by giorgiosironi** [comment]
Was just a placeholder for possible improvements, may be empty.

**Comment by giorgiosironi** [comment]
From standup: dump information in the `README` of `jats-ingester`, followed-up by a knowledge sharing meeting exploring Airflow concepts through the UI.

**Comment by giorgiosironi** [comment]
Should we use the next knowledge sharing slot on Oct 21 for the in-person part of this? Or something more focused to fewer team members? /cc @BlueReZZ

**Comment by BlueReZZ** [comment]
I more focused slot sounds better as a) a few people are away on your proposed date and b) would be good to have @de-code here for it too. This Friday (18th) seems sensible in that case.
