### ISSUE TITLE
jats-ingester uses postgres v11, RDS uses v10

### ISSUE THREAD

**Issue by diversemix** [libero/publisher#275]
Do we want to use RDS with the jats-ingester? If so probably best to use pg v10

**Comment by giorgiosironi** [comment]
Not sure from when, but seems supported now?
https://aws.amazon.com/rds/postgresql/why-postgresql-11/

**Comment by diversemix** [comment]
Great! ... we should probably pin a version to use across the whole of Libero for now, don't you think?

**Comment by giorgiosironi** [comment]
A single major version probably easy to maintain, but anything more specific?

**Comment by diversemix** [comment]
Nope - that sounds good enough, shall we say v11 then?

**Comment by giorgiosironi** [comment]
:+1: where to record this?

**Comment by diversemix** [comment]
Would probably be good to have an "Artifact Catalogue" or similar .... we should probably record licences too

**Comment by giorgiosironi** [comment]
This project has been archived, and the underlying issue of PostgreSQL version support on RDS doesn't seem to be a problem anymore.
