### ISSUE TITLE
Investigate hypermedia authorization patterns

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#277]
HATEOAS requires that the server side tells the client:
- what actions are available (in general, think about a grayed out button that you can't click)
- what actions can be performed by the user

Suggests an authentication and authorization model where the user identity in the frontend is the same as what is used to the server, which is different from authenticating a front end service like `journal` and `lax` (or other backends) do in Continuum to show or not show articles.

We can assume an authentication mechanism and investigate patterns for the authorization part. If there's tooling available, all the better.

**Comment by giorgiosironi** [comment]
Summarizing Kong's model used in Continuum, which is agnostic with respect to the media types used by the backend APIs:
- a [`Key Authentication`](https://docs.konghq.com/hub/kong-inc/key-auth/) plugin identifies the `consumer` as a particular application, like `journal`, using a `Authorization` header with a value corresponding to a secret key
- an [`ACL`](https://docs.konghq.com/hub/kong-inc/acl/) plugin used the `consumer` identity to map it to a group, which can be whitelisted [x]or blacklisted for a particular API (e.g. `/search`). `X-Consumer-Groups` is passed anyway to backends so they can check the groups by themselves.

**Comment by giorgiosironi** [comment]
What I can find out about `sci.pe`:
- front end requests have an `AuthSession` cookie which is opaque e.g. `ZW5nZWxiYXJ0LWRlbW86..._sBbkaEqF7gSqv8...`
- different "personas" of a Person are represented through [Roles](http://blog.schema.org/2014/06/introducing-role.html):
```
{
 "@context": "https://sci.pe",
 "@id": "action:actionId",
 "@type": "TagAction",
 "agent": {
  "@type": "Role",
  "roleName": "editor",
  "agent": {
   "@id": "user:jon",
   "@type": "Person"
  }
 },
 "object": "graph:graphId",
 "result": {
  "@type": "Tag",
  "name": "Linked data"
 }
}
```
- "If more granularity is needed (for which use case?), the name property of the Role can be used:
```
{
 "@context": "https://sci.pe",
 "@id": "http://example.com/role",
 "@type": "Role",
 "roleName": "editor",
 "name": "editor-in-chief",
 "agent": "user:jon"
}
```
- `hasDigitalDocumentPermission` example:
```
{
 "@context": "https://sci.pe",
 "@id": "http://example.com/periodical",
 "@type": "Periodical",
 "hasDigitalDocumentPermission": {
  "@type": "DigitalDocumentPermission",
  "grantee": {
   "@type": "Audience",
   "audienceType": "public"
  },
  "permissionType": "ReadPermission"
 }
}
```
- `WritePermission` is standard schema.org value, but there are more custom one like `ViewIdentityPermission` to model who can view the identity of whom e.g. inside peer review
- groups of people can be targeted as a `Audience`, again possibly with a `name` property for more granularity:
```
{
 "@context": "https://sci.pe",
 "@id": "http://example.com/audience",
 "@type": "Audience",
 "audienceType": "editor",
 "name": "editor-in-chief"
}
```
- An action [can be performed if](https://sci.pe/get-started/api) (are the conditions in `and`?):
  - The user performing the action corresponds to the action `agent` or, when the action agent identity is not defined, the user has a role (specified in the action’s object or scope) matching the `@id`, `roleName` and `name` (if any) of the action’s agent.
  - The role matching the action `agent` is granted with a WritePermission or AdminPermission for the object or scope of the action.
- An action can be viewed if:
  - The user requesting the action corresponds to the action `agent` or, the action `participant` or `recipient` properties (possibly including audiences) match a user role (defined in the action’s object or scope).
  - The role (or audience) matching the action `agent` is granted with a ReadPermission, WritePermission or AdminPermission.

**Comment by giorgiosironi** [comment]
I have no idea what OpenID Connect is but I frequently see it cited in this area, so taking a look.

**Comment by giorgiosironi** [comment]
- OAuth 2.0 (as we know from the ORCID case) supports the Authorization Code flow and the less safe Implicit flow (for client side apps). The latter does not allow obtaining the token through a back channel.
- OAuth for authentication is bad because there is no standard way to get the user's information.
- OpenID Connect builds on top of Auth to provide authentication. 5-10% layer on top.
  - ID token and `UserInfo` endpoint
  - Standard set of scopes (including `openid`)
(more coming)

**Comment by thewilkybarkid** [comment]
While not the focus here, just want to jot down potential 'users':

- Local service (probably authenticated; eg Search)
- External service (anonymous, could be authenticated; eg something wanting a list of articles)
- Local service on behalf of an end user (eg webapp)
- External service on behalf on an end user (eg Kriya?)

(Might not all be supported.)

**Comment by giorgiosironi** [comment]
Should we try to model these using the schema.org types used by sci.pe? Short on time today but can do tomorrow.

**Comment by giorgiosironi** [comment]
Everything I collected is in https://github.com/elifesciences/libero-hypermedia-walking-skeleton/pull/4, closing.
