### ISSUE TITLE
Add content-meta molecule pattern

### ISSUE THREAD

**Issue by discodavey** [libero/publisher#287]
Add content-meta molecule pattern to Storybook.

**Comment by davidcmoulton** [comment]
PR: https://github.com/libero/storybook/pull/31

**Comment by davidcmoulton** [comment]
Work on this ticket has exposed the problem that Storybook doesn't set `dir` attributes on the `<html>` element. See https://github.com/libero/storybook/pull/31#issuecomment-558597302 for a more detailed explanation. Merging https://github.com/libero/storybook/pull/31 is blocked until this is resolved.

**Comment by davidcmoulton** [comment]
Update: This PR has been merged, so this ticket is no longer blocked.
