### ISSUE TITLE
Publish Docker image for article-store

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#310]
Definition of Done:

- [x] https://hub.docker.com/u/liberoadmin lists a commit-tagged image for this project for every new `master` commit
- [x] https://hub.docker.com/u/liberoadmin has a `latest` image for this project pointing to the, well, latest commit-based tag
- [x] Relevant [`org.opencontainers.image.*` labels](https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys) are agreed and added 
- [x] Extract in `scripts` submodule 
- [x] https://github.com/libero/reviewer-client/blob/master/.github/workflows/ci.yml shares the `scripts` submodule

## Related

- Depends on https://github.com/libero/publisher/issues/340

**Comment by giorgiosironi** [comment]
In the [first run on `master`](https://github.com/libero/article-store/runs/370881889), the script was skipped:
```
Run .scripts/github/push-image.sh article-store
  .scripts/github/push-image.sh article-store
  shell: /bin/bash -e {0}
  env:
    IMAGE_TAG: 303714e04272951b3049b0e71c8b260aa930728c
    DOCKER_USERNAME: ***
    DOCKER_PASSWORD: ***
not pushing an image, we are not on master
```

**Comment by giorgiosironi** [comment]
Probably a typo in using `refs/head/` rather than `refs/heads/`.

**Comment by thewilkybarkid** [comment]
https://hub.docker.com/r/liberoadmin/article-store now available.

**Comment by giorgiosironi** [comment]
https://github.com/libero/reviewer-client/runs/375306068 is green. https://hub.docker.com/layers/liberoadmin/reviewer-client/ee630cdec6f8a9c3514aa38dcd30a058446c6849/images/sha256-98b012c3eb45d2271eb4b037dca3ba8f178888deb5d982460b76a85ba4a3c3e8 is there, it just took a few minutes for https://hub.docker.com/r/liberoadmin/reviewer-client/tags to add it to the list.
