### ISSUE TITLE
PUT and GET a single article version

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#32]
Following https://github.com/libero/schemas/pull/1/files:
- [ ] PUT `/articles/:id/versions/:version`
- [ ] GET `/articles/:id/versions/:version/front`

Summary:
- go for the `PUT /articles/:id/versions/:v` first
- validate that `:v` is greater than any existing version for article `:id` (it's an int so you can enforce this); support for silent correction can relax this later if needed
- POST would have to configure a generation strategy so it's for later

Experience from the walking skeleton suggests that storing most of the XML content as a blob rather than parsing all of it allows to be agnostic wrt most of to the schema. 

Sqlite is fine as a database to start out with.

**Comment by thewilkybarkid** [comment]
Yep, this is why we need to go through the sort out the tickets.

**Comment by giorgiosironi** [comment]
Removed from the milestone, so removing from the board.
