### ISSUE TITLE
XML requirements for references

### ISSUE THREAD

**Issue by FAtherden-eLife** [libero/publisher#333]
https://docs.google.com/document/d/1wvNFrJKUpsWv0JMga7HQIO2zXKF6t5ZHs0Q-M3dd6WY/edit

#### Google doc describing XML to support for:
- [x] MVP
- [ ] Post-MVP (if applicable)
- [ ] Never/no support (if applicable)

#### Schematron
- [x] Update `data-model` schematron branch

**Comment by fred-atherden** [comment]
Decision to (in part) postpone discovery of `<mixed-citation>`. Not possible to provide full requirements for post-MVP at this stage.

Will revisit once this work has been picked up in development.
