### ISSUE TITLE
Add Hydra Analyser to the Article Store's CI

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher#335]
Add [hydra-validator-analyse](https://www.npmjs.com/package/hydra-validator-analyse) to the Article Store's CI, which should help find issues with the Hydra implementation.

The tool can be tried at https://analyse.hypermedia.app/

## Tasks

- [x] Add to Article Store (https://github.com/libero/article-store/pull/33)

## Related

- Blocked by #314 (add Hydra).

**Comment by tpluscode** [comment]
As reference check HydraCG/api-examples#8
