### ISSUE TITLE
Introduce validation of XML

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#34]
The content store should refuse to ingest content that does not match the expected schema.

How would this work in Python? The RelaxNG schemas seems supported by e.g. [lxml](https://lxml.de/validation.html#relaxng). For the purpose of this task it can be assumed the schemas are committed somewhere in a folder inside the article-store (configuration will come later).

I'm not sure there's anything useful in https://github.com/libero/walking-skeleton/tree/master/article-store as this was probably not implemented.

Using this in an API depends on doing https://github.com/libero/libero/issues/32 first, but it should be produced as a standalone Python module first with its own unit test. Eventually this could become a library or a service used by Python/non-Python other services.

## References

-  [schema of an article front](https://github.com/libero/schemas/pull/1/files#diff-93231147fca40be10a6c6c2ed111f942)
- [sample of an article front](https://github.com/libero/schemas/pull/1/files#diff-c84bdbfd5f7bc0bbf30203a6589ce4e3)

**Comment by giorgiosironi** [comment]
`content-validator`?

**Comment by gnott** [comment]
``content-validator`` repo name (https://github.com/libero/content-validator) with a Python module name of ``libero-content-validator``.

**Comment by thewilkybarkid** [comment]
Trying to work out what the scope of `libero-content-validator` is. More general validating XML against an RNG schema, or the specific format of the content store API?

**Comment by gnott** [comment]
I was only aiming for the RELAX NG parts, the ``<content>`` found in Libero. It can be expanded to validate more like RAML, I guess, in the future, but I wasn't looking at it yet.

**Comment by thewilkybarkid** [comment]
I wasn't referring to RAML, but the schemas for other future services (eg search, event bus).
