### ISSUE TITLE
Maintain our own repo with our own eslint rules

### ISSUE THREAD

**Issue by nlisgo** [libero/publisher#355]
Definition of Done:

- [ ] create repo with our own eslint rules
- [ ] introduce the rules as a dependency in [article-store](https://github.com/libero/article-store)

## Related

Affects: https://github.com/libero/article-store/pull/114 (Article list async iterable)

**Comment by thewilkybarkid** [comment]
Closing in favour of https://github.com/libero/publisher/issues/375.
