### ISSUE TITLE
Decide RDF predicate and object for article PDF link

### ISSUE THREAD

**Issue by giorgiosironi** [libero/publisher#385]

**Comment by thewilkybarkid** [comment]
```json
{
  "@context": "http://schema.org",
  "type": "Article",
  "encoding": {
    "type": "MediaObject",
    "contentUrl": "http://example.com/article.pdf",
    "encodingFormat": "application/pdf"
  }
}
```

**Comment by thewilkybarkid** [comment]
Was going to see what http://sci.pe/ says, but seems to be unavailable.

**Comment by giorgiosironi** [comment]
https://github.com/science-periodicals/blob-store/blob/056d3b678734e4fef844d8c5d6fb03a24560e889/README.md#blobstoreputencoding-params--callback has a `sci.pe` example:
```
{
  '@id': 'encodingId',
  '@type': 'ImageObject',
  creator: 'bot:BlobStore',
  fileFormat: 'image/png',
  contentSize: 20402,
  name: 'pieuvre.png',
  contentUrl: 'http://example.com/encodingId',
  encodesCreativeWork: 'resourceId',
  dateCreated: '2015-04-17T15:37:00.528Z',
  contentChecksum: {
    '@type': 'Checksum',
    checksumAlgorithm: 'sha256',
    checksumValue: 'DmjKGM5ZHmyeDdVxUpoCADhybkfISowriovdhgbXVBA='
  }
}
```
`ImageObject` is a subclass of `MediaObject` but there isn't a relevant subclass for PDF files. `fileFormat` in there is superseded by `encodingFormat`.

**Comment by giorgiosironi** [comment]
Don't think there's value in adding other properties like in this example now. Anything else to investigate before settling on [this](https://github.com/libero/publisher/issues/385#issuecomment-600050063) format?

**Comment by thewilkybarkid** [comment]
Don't think so. In the future might need a way to discriminate between PDFs (eg eLife has 2), but for now it's fine.
