### ISSUE TITLE
Dashboard header bar with logo

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#48]
## Problem / Motivation
- WHO As a production team member or journal staff
- WHAT I would like a visual reminder of what software I am using
- WHEN I am on the dashboard
- WHY so that I am reassured that I have opened the correct tool

## Proposed solution
- A logo on the top left-hand corner (see mockup below)
- Clicking on the logo will take the user back to the dashboard landing page which is the 'In Progress' tab

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Decisions
- The header won't have any links in the MVP so no need to build the fly-out menu for the mobile version

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes
- Desktop view
![mvp-app-bar-desktop](https://user-images.githubusercontent.com/39725642/46745871-ce714500-cca5-11e8-9d31-a3f3a0f2cfea.png)

- Mobile view
<img width="537" alt="screen shot 2018-10-10 at 16 04 21" src="https://user-images.githubusercontent.com/39725642/46746133-4b042380-cca6-11e8-9669-a5e4adb4833a.png">

**Comment by Melissa37** [comment]
@Maelplaine has the Libero logo been used as an example or is the idea that it indicates the user is on Libero?
I'd assumed the logo would be the publisher's logo and this is more about branding than
>what software I am using
or
> I am reassured that I have opened the correct tool

**Comment by Maelplaine** [comment]
@Melissa37 We are planning to use Libero's logo for the MVP. In a future version, this logo will be customisable and the publisher will have the option to replace it with their logo.
