### ISSUE TITLE
Information displayed on a each item in a a list of manuscripts

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#52]
## Problem / Motivation
- WHO As a production team member or journal staff
- WHEN looking at a list of manuscripts
- WHAT I would like to have enough information to assess if the manuscript I found in the list is the one I am looking for
- WHY so that I do not waste time opening the article details page for more information

## Proposed solution

- The following pieces of information should be displayed (see screenshot below for layout):
_ Manuscript title
_ Corresponding author name
_ Planned publication data
_ Status (or error message if in the errors list)
_ DOI url
_ Version number  (eg. ver 1)
_ Run number (eg. run 1)

- There are several types of list item, with different states:

_Article in In progress: "Requires checking"
_Article in In progress: "Ready to publish"
_Article in Errors: "Error"
_Article in In progress: "Publishing"
_Article in Published: "Published"
_Issue in Issues: Ready to publish"
_Issue in Issues: "Publishing"
_Issue in Issues: "Publishing"
_Issues in "Select an issue" list - different visual state for selecting

- Display last version and run of an article that got to a published event (if any)
- Updated / new versions when published will replace previous version

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Decisions & notes
- A corrected Typo will create a new version of the article if it has already been published
- An official correction is different than a typo correction. A link will be displayed on the front-end and will redirect the user to the Correction Article.
- The MVP will support the versioning workflow
- The publication date comes from the XML

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

<img width="923" alt="01-in_progress_png" src="https://user-images.githubusercontent.com/39725642/46880314-3fe4fb00-ce40-11e8-9d41-e0aa64bc732d.png">

**Comment by chugginselifesciences** [comment]
All list items and states below:

Article - "Requires Checking" - default
![image](https://user-images.githubusercontent.com/41907215/47780468-5d94da00-dcf3-11e8-9620-a17cb8813297.png)

Article - "Requires Checking" - updating (i.e. new run on this article DOI in progress)
![image](https://user-images.githubusercontent.com/41907215/47780547-7ef5c600-dcf3-11e8-88d3-1bb4870ef1b9.png)

Article - "Ready to Publish" - default
![image](https://user-images.githubusercontent.com/41907215/47780594-8fa63c00-dcf3-11e8-8962-904a501d778b.png)

Article - "Ready to Publish" - updating
![image](https://user-images.githubusercontent.com/41907215/47780608-9b91fe00-dcf3-11e8-82ea-975d3cd31eca.png)

Article - "Error" - default
![image](https://user-images.githubusercontent.com/41907215/47780621-a6e52980-dcf3-11e8-8a76-f750990e9225.png)

Article - "Error" - updating
![image](https://user-images.githubusercontent.com/41907215/47780642-b2385500-dcf3-11e8-87d9-c01acae3080d.png)

Article - "Publishing"
![image](https://user-images.githubusercontent.com/41907215/47780724-d98f2200-dcf3-11e8-969e-7b2d76d6edfb.png)

Article - "Published [time]"
![image](https://user-images.githubusercontent.com/41907215/47780772-f4fa2d00-dcf3-11e8-9841-66d26fa2f78f.png)

**Comment by chugginselifesciences** [comment]
Mobile layouts:

Article - "Requires Checking" - default & updating
![image](https://user-images.githubusercontent.com/41907215/47781088-c2046900-dcf4-11e8-8002-58668086e63f.png)

Article - "Ready to Publish" - default and updating
![image](https://user-images.githubusercontent.com/41907215/47781103-cfb9ee80-dcf4-11e8-95d1-ba54eef449bd.png)

Article - "Error" - default and updating
![image](https://user-images.githubusercontent.com/41907215/47781137-dfd1ce00-dcf4-11e8-9628-91b3020935c2.png)

Article - "Publishing" and "Published [time]"
![image](https://user-images.githubusercontent.com/41907215/47781174-f8da7f00-dcf4-11e8-89ec-6557580b99e9.png)

**Comment by Melissa37** [comment]
>_ Version number

I have a concern that v1 could be confused with volume 1 so wonder whether there is another way to represent this value - ver seems to be used in some communities?

**Comment by Maelplaine** [comment]
@Melissa37 Thanks for flagging this. I will update the ticket description
