### ISSUE TITLE
Error counter in error tab title

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#53]
## Problem / Motivation
 
- WHO As a production team member or journal staff
- WHAT I would like to know if errors are waiting to be fixed
- WHEN and I would like to be able to know wherever I am on the dashboard
- WHY so that I am reminded to fix them asap

## Proposed solution

- An error counter next to the 'Errors' tab title (see screenshot below)
- The number of errors is white and in a red circle
- Error number = number of articles where current run produced an error
- When there is no error the counter is not showing

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Clarification needed and assumptions

- A question
- An assumption

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

<img width="1018" alt="04-errors-2-errors_list_png" src="https://user-images.githubusercontent.com/39725642/47024903-8301df80-d15a-11e8-89e7-6e1ad594a5c7.png">

**Comment by Melissa37** [comment]
👍
