### ISSUE TITLE
Dashboard 'In Progress' tab

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#55]
## Problem / Motivation
 
- WHO As a production team member or journal staff
- WHEN logging in in Libero's dashboard
- WHAT I would like to see a list of the manuscripts that require my attention before being published
- WHY so that I know where to focus my attention

## Proposed solution

- The manuscripts are sorted by run date and time, the most recent ones being at the top.
- Article state is determined by the last completed Run

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Decisions
- There is no need to show VOR for the MVP

## Clarification needed and assumptions

- ??

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

![01-in progress](https://user-images.githubusercontent.com/39725642/47031940-fca0ca00-d168-11e8-8b4a-9a55d202cc69.png)

**Comment by Melissa37** [comment]
👍
