### ISSUE TITLE
Dashboard 'Article Details' page

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#65]
## Problem / Motivation
- WHO As a production team member or journal staff
- WHEN as soon as an article has been ingested
- WHAT I would like to be able to see more details about an article
- WHY so I can see the history of a manuscript

## Proposed solution
- An 'article details' page to display a short description of the article status
- That page allows users to scroll through the different versions and run (see screenshot) 
- Some actions buttons will be displayed depending on the status of the article (will be done as part of the following ticket: #66)

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Decisions
- There is no need to display the ingestion steps of a manuscript that has been successfully ingested
- If a mananuscript has an error when ingested, then we only display the error message

## Clarification needed and assumptions
- Can a manuscript have more than one error when it is ingested?
> @thewilkybarkid  can you answer this question?
- Do we need to display timezone for each event? Can we assume that the publisher will know the system is using their local timezone for the MVP and display the timezone in a future release?
> Matteo are you happy with this approach?  

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

<img width="777" alt="07-article-detail_png" src="https://user-images.githubusercontent.com/39725642/47494030-a3abf280-d848-11e8-8531-a78e33f32fd3.png">

**Comment by Melissa37** [comment]
👍 and agree with the clarification needed question!

**Comment by chugginselifesciences** [comment]
Some updates have been made following a workshop, and some layout tweaks following user testing:

**"Errors" - When an article is in an error state (i.e. something technical failed, and the article cannot be previewed or published):**

![image](https://user-images.githubusercontent.com/41907215/51535951-e4180e00-1e41-11e9-8bb8-7b73c084681d.png)

**"Requires Checks" - When an article is in a state of "Requires checks" (didn't fail, but needs checks before it can be published):**

![image](https://user-images.githubusercontent.com/41907215/51535966-f003d000-1e41-11e9-9385-3c5e95e71232.png)

**"Ready to publish" - When an article has passed quality checks, and is ready to be published". But it's publication date is in the future**

![image](https://user-images.githubusercontent.com/41907215/51535977-fdb95580-1e41-11e9-941c-28a656dedc07.png)


**"Ready to publish" (today) - ready to publish and intended publication is same as today's date:**

![image](https://user-images.githubusercontent.com/41907215/51536023-1d507e00-1e42-11e9-93a2-5e92be70fe97.png)

**"Publishing": A user has opted to publish the article, and it is currently in the process of "publishing"**

![image](https://user-images.githubusercontent.com/41907215/51536065-407b2d80-1e42-11e9-8354-211e30ec96cf.png)

**"Published" - the article publication is complete:**

![image](https://user-images.githubusercontent.com/41907215/51536093-5688ee00-1e42-11e9-98ba-76d00de5ed91.png)

**Comment by thewilkybarkid** [comment]
> Can a manuscript have more than one error when it is ingested?

Yes, the list of steps that it goes through isn't necessarily a sequential list (it's a [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph)).

**Comment by chugginselifesciences** [comment]
Thanks Chris. In that case I'm wondering if we can simply show the errors, or would users aiming to fix it need the context of "the rest of the steps during ingest" to understand the problem? If things can happen in different orders, does seeing the other/successful steps help solve problems?

It seems to me the simple option (in terms of user experience) would be:

**For 1 error**

![image](https://user-images.githubusercontent.com/41907215/51543154-d8821280-1e54-11e9-9a63-27f5fa31218d.png)

**For multiple errors**

![image](https://user-images.githubusercontent.com/41907215/51543179-e6379800-1e54-11e9-8243-ee2aed4d8628.png)


**Or with all steps for additional context (you would click a step to show details somehow)**

![image](https://user-images.githubusercontent.com/41907215/51543225-fe0f1c00-1e54-11e9-8a5d-7306207e7355.png)
