### ISSUE TITLE
Dashboard 'Article Details' actions buttons

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#66]
## Problem / Motivation
- WHO As a production team member or journal staff
- WHEN on an article details page
- WHAT I would like to be able to choose an action quickly
- WHY so that the article can be previewed, added to an issue, scheduled...

## Proposed solution
- Buttons are displayed at the bottom of the page in the fixed footer
- Grey out the actions buttons while a new run of the article being viewed is ongoing

## Decisions
- A new run of a published article is a revision, status text is different but action button labels remain the same that means: 'Require checking' = 'Check revision', 'Read to publish' = 'Revision ready' and 'Published' = 'Revision published'

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Clarification needed and assumptions

- A question
- An assumption

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

@chugginselifesciences Could you add some screenshots of the Article details page with the action buttons?

**Comment by Melissa37** [comment]
@Maelplaine can you add some UI screenshots?

**Comment by chugginselifesciences** [comment]
Article detail - "Requires checking"
![article-detail-requires-checking](https://user-images.githubusercontent.com/41907215/48013891-5586d100-e11d-11e8-8f5c-c24cea5e3d95.png)

Article detail - "Ready to publish"
![article-detail-ready-to-publish](https://user-images.githubusercontent.com/41907215/48013917-67687400-e11d-11e8-967c-fac46f9fc2fa.png)

Article detail - "Error"
![article-detail-error](https://user-images.githubusercontent.com/41907215/48013931-70594580-e11d-11e8-8046-cd24519acdc4.png)

Article detail - "Publishing"
![article-detail-publishing](https://user-images.githubusercontent.com/41907215/48013946-78b18080-e11d-11e8-8ce8-5ce5eccf5488.png)

Article detail - "Published"
![article-detail-published](https://user-images.githubusercontent.com/41907215/48013959-81a25200-e11d-11e8-9591-7d50b5b37541.png)

**Comment by Melissa37** [comment]
A couple of questions:

- I see the ADD TO ISSUE button greyed out if it's not yet published. However, when an article is published, the ADD TO ISSUE button is still greyed out. At what point can you add to an issue?

- Did we decide on the times being added to the events (ie Published 12.22). Is the 24 hour clock going to be used and will the clock be set to a particular time zone for the publisher, so if someone publishes when they are traveling the time zone is still shown in their "home" time?

- I assume these screenshots will follow the decisions made in https://github.com/libero/libero/issues/65, that is some of the details will not be displayed?

Comment:
>A new run of a published article is a correction

This is not correct, a new run is a revised submission to the platform. A correction has a different meaning and is a change to an article AFTER it's been published.

Thanks!

**Comment by chugginselifesciences** [comment]
> * I assume these screenshots will follow the decisions made in #65, that is some of the details will not be displayed?

Yes these screenshots pre-date the workshop where a lot of decisions were made so some details in these will be no longer relevant. However changes to the the buttons in the footer bar were not raised, so those should still be correct.
<br/>
> * I see the ADD TO ISSUE button greyed out if it's not yet published. However, when an article is published, the ADD TO ISSUE button is still greyed out. At what point can you add to an issue?

Those are actually the "secondary" button style, used for options where there is another action available that requires more emphasis (see the screenshot for "Ready to publish" where there is a "publish now" option in the primary button style and "add to issue" in the secondary button style. The emphasis is on the publish now button) I continued the use of the secondary button style through to the publishing and published states, so the buttons are not greyed out or inactive in either instance.

If it's confusing we can change them to the primary button style when they are the only available option. The intention is that it could be added to an issue at any time once QC checks are passed. We are using the "primary" and "secondary" button styles throughout xPub so would be ideal to keep consistent.
<br/>

> * Did we decide on the times being added to the events (ie Published 12.22). Is the 24 hour clock going to be used and will the clock be set to a particular time zone for the publisher, so if someone publishes when they are traveling the time zone is still shown in their "home" time?

If I remember correctly we agreed that the time zone would be based on the location of the publisher (not the user) so for MVP it would be based on the UK. And I believe that 24hr clock is more appropriate internationally. Perhaps @Maelplaine or @thewilkybarkid can confirm or elaborate.

Thanks

**Comment by Maelplaine** [comment]
@Melissa37 I have changed the word 'correction' to 'revision' in the ticket description above. 

Regarding the time zone, here are my notes from our mockups review meeting that happened on  14/09/18

_it should be fixed to UK time for eLife or use the publisher timezone. We could just use the UK time or UTC for the MVP
Suggest using UK time for MVP, then ensuring the “publisher’s local time” determines when somebody can publish, not the user’s local time (e.g. Melissa in US being blocked from publishing at correct time because technically it's the wrong date in the US but correct in UK)_

We could add the time zone and publishing date and time on the publish article confirmation modal, but this feature appears to be nice to have and isn't required for the MVP.

**Comment by Melissa37** [comment]
👍

**Comment by Maelplaine** [comment]
@Melissa37 I will add a clarification needed question for Matteo to answer on this ticket #65 . I think we could live without the mention of the timezone in the event for the MVP

**Comment by Melissa37** [comment]
Agree.
M
