### ISSUE TITLE
Dashboard 'Errors' tab

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#69]
## Problem / Motivation
- WHO As a production team member or journal staff
- WHEN & WHERE when working in the dashboard
- WHAT I would like to be able to see all the manuscripts blocked by errors in one place
- WHY so that I do not waste time looking for them in the 'In Progress' list or other tabs

## Proposed solution

- The manuscripts are sorted by run date and time, the most recent ones being at the top.

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Clarification needed and assumptions

- ???

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

![04-errors-2-errors_list_png](https://user-images.githubusercontent.com/39725642/47911851-7f769400-de8e-11e8-941e-68c30fa05bcd.png)

**Comment by Melissa37** [comment]
👍
