### ISSUE TITLE
Dashboard 'Published' tab

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#70]
## Problem / Motivation
- WHO As a production team member or journal staff
- WHEN & WHERE when working in the dashboard
- WHAT I would like to be able to see all the recently published articles in one place
- WHY so that I can use this page as an archive and consult it when I need to found out about the history log of a published article

## Proposed solution

- The articles are sorted by publication date and time, the most recent ones being at the top.

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Clarification needed and assumptions

-  How many articles do we allow to appear on this list to appear?
- Are we using pagination to display the others or a 'Load more' button at the bottom of the page?

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

![05-published-list](https://user-images.githubusercontent.com/39725642/47920539-303e5c80-deaa-11e8-8f68-f31fa8dd59fc.png)

**Comment by Melissa37** [comment]
Question - what determines the end of this list? Does it all a certain number of articles on this list to appear or is it based on date (ie goes back 1 week or month)?

**Comment by Melissa37** [comment]
👍
