### ISSUE TITLE
Dashboard article preview

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#71]
## Problem / Motivation
- WHO As a production team member or journal staff
- WHEN when an article just got ingested
- WHAT I would like to be able to preview the article before publishing it
- WHY so that I can do some final quality checks

## Proposed solution
- Replicate the preview functionality used in eLife's current dashboard
- Open the article preview in a new tab
- Clicking on the 'Preview' button opens the 'Accept article' modal (see #72 )

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Clarification needed and assumptions
- The users will have to fill in another login and password to preview the article

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes
![09-preview](https://user-images.githubusercontent.com/39725642/47921935-bad48b00-dead-11e8-82f6-17406df175a1.png)

**Comment by Melissa37** [comment]
👍
