### ISSUE TITLE
Dashboard QC 'Accept article' modal 

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#72]
## Problem / Motivation
- WHO As a production team member or journal staff
- WHEN clicking on preview
- WHERE on the article details page
- WHAT I would like to be able to indicate if the manuscript is ready to be published 
- WHY so that my colleagues and I know that the last checks have been done on this article

## Proposed solution

- A modal pops up after clicking on 'preview' (see screenshot)
- The modal has 2 buttons: 'Cancel' and 'Accept'
- Both buttons are taking the user back to the article details page, but if the user clicks on 'Accept' then the manuscript status is changed 'Ready to publish'

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Clarification needed
- What happens if someone clicks on 'Preview', does the QC but closes the Dashboard tab in their browser before clicking on 'Cancel' or 'Accept'?
- The word 'Accept' can be confusing in the context of the publication of a manuscript. Which word can we use to replace it?
> Matteo suggested "Confirm" instead. @Melissa37 Is this word suitable for your team? 

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

![10-modal](https://user-images.githubusercontent.com/39725642/47923294-f3299880-deb0-11e8-903b-d1240d3d0be2.png)

**Comment by Melissa37** [comment]
>Matteo suggested "Confirm" instead. @Melissa37 Is this word suitable for your team?

👍

**Comment by chugginselifesciences** [comment]
Proposed updates to wording:

For articles with publication date NOT today:

![image](https://user-images.githubusercontent.com/41907215/51675861-d5aa2d80-1fcc-11e9-9032-e6b00c2a19c8.png)

For articles with publication date = today:


![image](https://user-images.githubusercontent.com/41907215/51675833-c32ff400-1fcc-11e9-8179-245b0f180a34.png)
