### ISSUE TITLE
Dashboard Publish action confirmation modal

### ISSUE THREAD

**Issue by Maelplaine** [libero/publisher#73]
## Problem / Motivation
- WHO As a production team member or journal staff
- WHEN clicking on 'Publish now'
- WHERE on the article details page
- WHAT I would like to be asked to confirm my action
- WHY so that I can cancel it if that was a mistake

## Proposed solution

- A modal pops up after clicking on 'Publish Now'
- The modal has 2 buttons: 'Cancel' and 'Publish now'  (see screenshot)
- Both buttons are taking the user back to the article details page, but if the user clicks on 'Publish now' then the manuscript status is changed 'Published: HH:MM'. HH:MM is the time when the manuscript was published

## Tasks

- [ ] A descriptive of a task
- [ ] A description

## Assumption
- It would be useful to display the date and publishing time (+timezone) on the modal, but this isn't required for the MVP

## Technical notes
- We could use this technology 
- More notes or suggestions

## User interface / Wireframes

![publish-6-confirm publication modal](https://user-images.githubusercontent.com/39725642/48189531-55165200-e338-11e8-885d-3ab30a0d320e.png)

**Comment by Melissa37** [comment]
👍
