### ISSUE TITLE
Change "In progress" list to "Checking" and "Ready to publish" (dashboard)

### ISSUE THREAD

**Issue by chugginselifesciences** [libero/publisher#91]
Following some work on the xPub dashboard (with a view to building a single consistent dashboard across xPub and Libero) I’ve been exploring changes to the navigation of different lists/tabs.

Currently in the Libero UI we have a single tab named “in progress” that contains ‘ingested’ articles that require quality checks. Once checked they enter a state of “ready to publish”. Following the changes we made to how articles are checked and published as a result of testing with the production team and the workshops with IJM, I think this could now be improved.

**Current design:**

![image](https://user-images.githubusercontent.com/41907215/51315877-2230be80-1a4b-11e9-9bc0-18e6eed3c3c2.png)

When an article passes "checks", it changes state to "Ready to publish" and remains in the list until published. We therefore have a list with a mixture of articles in "Requires checks" and "Ready to publish" states.

**Proposal:**

![image](https://user-images.githubusercontent.com/41907215/51316240-f6fa9f00-1a4b-11e9-97bd-2212ef40a726.png)

![image](https://user-images.githubusercontent.com/41907215/51316256-02e66100-1a4c-11e9-9c10-c967721d5db5.png)

I propose a change to two lists - "Checking" for articles in "Requires checks" state, and "Ready to publish" for articles in a "Ready to publish" state. That way if users choose to leave articles in a "Ready to publish" for example to delay publication, they would risk being mixed in with those in "Requires checks" state.

Note the side menu is part of some in progress design updates to the xPub dashboard. This design allows us more space to add necessary menu items (e.g. an archive) and helps work towards a consistent or single dashboard for xPub and Libero.

**Comment by chugginselifesciences** [comment]
@Melissa37 if there are no obvious problems with this change I'd like to update the prototype and test briefly with your team, and share with IJM, so we can make a decision before development on the dashboard.

**Comment by Melissa37** [comment]
@chugginselifesciences Thanks, it makes sense to me and I hope the rest of the production team think so too!
Thanks
M
